# Generated by Django 3.2.8 on 2021-10-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='FirstName',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='LastName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='Number',
            field=models.IntegerField(),
        ),
    ]
