# Generated by Django 3.2.8 on 2021-10-11 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fscohort', '0002_auto_20211011_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'ordering': ['Number'], 'verbose_name_plural': 'Student_List'},
        ),
        migrations.AlterModelTable(
            name='students',
            table='Student_Table',
        ),
    ]
